apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sleep-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sleep
  source:
    repoURL: https://github.com/Kevinom57/argocd-directory/
    targetRevision: HEAD
    path: 011-sync-option
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

