apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-directory-sync
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/Kevinom57/argocd-directory.git
      path: 010-sync-policies/exposition
      targetRevision: HEAD
    - repoURL: https://github.com/Kevinom57/argocd-directory.git
      path: 010-sync-policies/workload
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
